services:
  frontend:
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "3000:3000"
